var data = require('./contactData.js');
exports.readObj = {
	crmlink_xpath : "//div[contains(text(),'CRM')]",
	contactslink_xpath : "//div[contains(text(),'Contacts')]",
	newbutton_xpath : ".//*[@id='app_postbooks_navigator_newButton']",
	cnumber_xpath : ".//*[@id='app_postbooks_workspaceContainer_workspace_inputWidget2_input']",
	active_xpath : "#app_postbooks_workspaceContainer_workspace_checkboxWidget_input",
	cfname_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_inputWidget3_input']",
	cmname_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_inputWidget4_input']",
	clname_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_inputWidget5_input']",
	addrsearch_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_addressWidget_searchButton']",
	addrtext_xpath : "//div[contains(text(),'Ungargasse 60 ')]",
	jobtitle_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_inputWidget7_input']",
	email_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_inputWidget8_input']",
	phone_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_inputWidget9_input']",
	charecnew_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_contactCharacteristicsWidget_newButton']",
	charecinput_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_contactCharacteristicsWidget_repeater_ownerProxy_characteristicItem_inputWidget_input']",
	cnotes_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_textArea_input']",
	caccount_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_accountWidget_input']",
	cowner_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_userAccountWidget_input']",
	commentnew_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_contactCommentBox_repeater_ownerProxy_repeaterItem_commentType_pickerButton']",
	commenttype_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_contactCommentBox_repeater_ownerProxy_repeaterItem_commentType_picker_menuItem14']",
	commentinput_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_contactCommentBox_repeater_ownerProxy_repeaterItem_textArea_input']",
	savebutton_xpath : "//*[@id='app_postbooks_workspaceContainer_saveButton']",
	heading_xpath : "//*[@id='app_postbooks_workspaceContainer_title']",
	addressEditButton_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_addressWidget_editButton']",
	addressLine1_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_addressWidget_line1']",
	addressDoneButton_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_addressWidget_button']",
	charecRead_xpath : "//input[contains(@value,'" + data.VARIABLES.contact_bday +"')]",
	documentsLink_xpath : "//div[contains(text(),'Documents')]",
	documentAttach_xpath: "//div[@id='app_postbooks_workspaceContainer_workspace_contactDocumentsBox_attachButton']",
	documentPurpose_xpath: "//button[contains(text(),'Related to')]",
	documentType_xpath: "//div[contains(text(),'Account')]",
	documentOk_xpath : "//*[@id='app_postbooks_workspaceContainer_workspace_contactDocumentsBox_button']",
	documentSearch_xpath : ".//*[@id='app_postbooks_searchContainer_list_listAttr'][contains(text(),'1001')]",
	documentAccount_xpath : ".//*[@id='app_postbooks_workspaceContainer_workspace_contactDocumentsBox_list_listAttr2'][contains(text(),'1001')]",
	documentAccount1_xpath : ".//*[@id='app_postbooks_workspaceContainer2_workspace_contactDocumentsBox_list_listAttr2'][contains(text(),'1001')]",
	refreshButton_xpath : ".//*[@id='app_postbooks_navigator_refreshButton']"
	
} 
exports.readObj1 = {
	crmlink_xpath : "//div[contains(text(),'CRM')]",
	contactslink_xpath : "//div[contains(text(),'Contacts')]",
	newbutton_xpath : ".//*[@id='app_postbooks_navigator_newButton']",
	cnumber_xpath : ".//*[@id='app_postbooks_workspaceContainer2_workspace_inputWidget2_input']",
	active_xpath : "#app_postbooks_workspaceContainer2_workspace_checkboxWidget_input",
	cfname_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_inputWidget3_input']",
	cmname_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_inputWidget4_input']",
	clname_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_inputWidget5_input']",
	addrsearch_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_addressWidget_searchButton']",
	addrtext_xpath : "//div[contains(text(),'Ungargasse 60 ')]",
	jobtitle_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_inputWidget7_input']",
	email_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_inputWidget8_input']",
	phone_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_inputWidget9_input']",
	charecnew_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_contactCharacteristicsWidget_newButton']",
	charecinput_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_contactCharacteristicsWidget_repeater_ownerProxy_characteristicItem_inputWidget_input']",
	cnotes_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_textArea_input']",
	caccount_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_accountWidget_input']",
	cowner_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_userAccountWidget_input']",
	commentnew_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_contactCommentBox_repeater_ownerProxy_repeaterItem_commentType_pickerButton']",
	commenttype_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_contactCommentBox_repeater_ownerProxy_repeaterItem_commentType_picker_menuItem14']",
	commentinput_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_contactCommentBox_repeater_ownerProxy_repeaterItem_textArea_input']",
	savebutton_xpath : "//*[@id='app_postbooks_workspaceContainer2_saveButton']",
	heading_xpath : "//*[@id='app_postbooks_workspaceContainer2_title']",
	addressEditButton_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_addressWidget_editButton']",
	addressLine1_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_addressWidget_line1']",
	addressDoneButton_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_addressWidget_button']",
	charecRead_xpath : "//input[contains(@value,'" + data.VARIABLES.contact_bday +"')]",
	documentAttach_xpath: "//*[@id='app_postbooks_workspaceContainer2_workspace_contactDocumentsBox_attachButton']",
	documentPurpose_xpath: "//button[contains(text(),'Related to')]",
	documentType_xpath: "//div[contains(text(),'Account')]",
	documentOk_xpath : "//*[@id='app_postbooks_workspaceContainer2_workspace_contactDocumentsBox_button']",
	documentSearch_xpath : ".//*[@id='app_postbooks_searchContainer_list_listAttr'][contains(text(),'1001')]",
	documentAccount_xpath : ".//*[@id='app_postbooks_workspaceContainer_workspace_contactDocumentsBox_list_listAttr2'][contains(text(),'1001')]",
	documentAccount1_xpath : ".//*[@id='app_postbooks_workspaceContainer2_workspace_contactDocumentsBox_list_listAttr2'][contains(text(),'1001')]",
	refreshButton_xpath : ".//*[@id='app_postbooks_navigator_refreshButton']"	
} 
